vim.keymap.set('n', '<Esc>', '<cmd>nohlsearch<CR>')
vim.keymap.set('n', '<leader>q', vim.diagnostic.setloclist, { desc = 'Open diagnostic [Q]uickfix list' })
vim.keymap.set('n', '<leader>k', vim.diagnostic.open_float)
vim.keymap.set('n', ']g', function()
  vim.diagnostic.jump { count = 1, float = true }
end)
vim.keymap.set('n', '[g', function()
  vim.diagnostic.jump { count = -1, float = true }
end)
vim.keymap.set('n', '<leader>el', '<cmd>vsplit<CR>')
vim.keymap.set('n', '<leader>ej', '<cmd>split<CR>')
vim.keymap.set('n', '<C-x>', '<cmd>bp<bar>sp<bar>bn<bar>bd<CR>')
vim.keymap.set('n', '<C-w>', '<cmd>bnext<CR>')
vim.keymap.set('n', '<C-q>', '<cmd>bprev<CR>')
vim.keymap.set('t', '<Esc><Esc>', '<C-\\><C-n>', { desc = 'Exit terminal mode' })
vim.keymap.set('n', 'K', vim.lsp.buf.hover)
